CREATE DATABASE ProjectManagerSPADB
Go

USE ProjectManagerSPADB
Go

CREATE TABLE ParentTask
(
Parent_ID INT PRIMARY KEY IDENTITY(1,1),
Parent_Task VARCHAR(100)
)
GO

CREATE TABLE Project
(
Project_ID INT PRIMARY KEY IDENTITY(1,1),
Project VARCHAR(100),
Start_Date DATETIME NOT NULL,
End_Date DATETIME NOT NULL,
Priority INT
)
GO

CREATE TABLE Task
(
Task_ID INT PRIMARY KEY IDENTITY(1,1),
Parent_ID INT FOREIGN KEY REFERENCES ParentTask (Parent_ID),
Project_ID INT FOREIGN KEY REFERENCES Project (Project_ID),
Task VARCHAR(100),
Start_Date DATETIME NOT NULL,
End_Date DATETIME NOT NULL,
Priority INT,
Status BIT NOT NULL
)
GO

CREATE TABLE Users
(
	User_ID INT PRIMARY KEY IDENTITY(1,1),
	FirstName varchar(30)  NOT NULL,
    LastName varchar(30)  NOT NULL,
    EmployeeID varchar(6)  NOT NULL,
	Project_ID INT FOREIGN KEY REFERENCES Project (Project_ID),
	Task_ID INT FOREIGN KEY REFERENCES Task(Task_ID)
)
GO
